# Generated by Django 5.1.15 on 2026-09-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=1000)),
                ('style', models.CharField(max_length=50)),
                ('aspect_ratio', models.CharField(max_length=20)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Generation',
                'verbose_name_plural': 'Image Generations',
                'ordering': ['-created_at'],
            },
        ),
    ]
